/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImpressionIndexRouteImport } from './routes/impression.index'
import { Route as ImpressionEmbroideryRouteImport } from './routes/impression.embroidery'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressionIndexRoute = ImpressionIndexRouteImport.update({
  id: '/impression/',
  path: '/impression/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressionEmbroideryRoute = ImpressionEmbroideryRouteImport.update({
  id: '/embroidery',
  path: '/embroidery',
  getParentRoute: () => ImpressionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/impression/embroidery': typeof ImpressionEmbroideryRoute
  '/impression/': typeof ImpressionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/impression/embroidery': typeof ImpressionEmbroideryRoute
  '/impression': typeof ImpressionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/impression/embroidery': typeof ImpressionEmbroideryRoute
  '/impression/': typeof ImpressionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/impression/embroidery' | '/impression/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/impression/embroidery' | '/impression'
  id: '__root__' | '/' | '/contact' | '/impression/embroidery' | '/impression/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  ImpressionIndexRoute: typeof ImpressionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impression/': {
      id: '/impression/'
      path: '/impression'
      fullPath: '/impression/'
      preLoaderRoute: typeof ImpressionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impression/embroidery': {
      id: '/impression/embroidery'
      path: '/embroidery'
      fullPath: '/impression/embroidery'
      preLoaderRoute: typeof ImpressionEmbroideryRouteImport
      parentRoute: typeof ImpressionRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  ImpressionIndexRoute: ImpressionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
