/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RepresentantsRouteImport } from './routes/representants'
import { Route as ImpressionRouteImport } from './routes/impression'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImpressionIndexRouteImport } from './routes/impression.index'
import { Route as ServicesPromotionalClothingRouteImport } from './routes/services.promotional-clothing'
import { Route as ImpressionSilkscreenRouteImport } from './routes/impression.silkscreen'
import { Route as ImpressionEmbroideryRouteImport } from './routes/impression.embroidery'
import { Route as ImpressionDtfRouteImport } from './routes/impression.dtf'

const RepresentantsRoute = RepresentantsRouteImport.update({
  id: '/representants',
  path: '/representants',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressionRoute = ImpressionRouteImport.update({
  id: '/impression',
  path: '/impression',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressionIndexRoute = ImpressionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ImpressionRoute,
} as any)
const ServicesPromotionalClothingRoute =
  ServicesPromotionalClothingRouteImport.update({
    id: '/services/promotional-clothing',
    path: '/services/promotional-clothing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ImpressionSilkscreenRoute = ImpressionSilkscreenRouteImport.update({
  id: '/silkscreen',
  path: '/silkscreen',
  getParentRoute: () => ImpressionRoute,
} as any)
const ImpressionEmbroideryRoute = ImpressionEmbroideryRouteImport.update({
  id: '/embroidery',
  path: '/embroidery',
  getParentRoute: () => ImpressionRoute,
} as any)
const ImpressionDtfRoute = ImpressionDtfRouteImport.update({
  id: '/dtf',
  path: '/dtf',
  getParentRoute: () => ImpressionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/impression': typeof ImpressionRouteWithChildren
  '/representants': typeof RepresentantsRoute
  '/impression/dtf': typeof ImpressionDtfRoute
  '/impression/embroidery': typeof ImpressionEmbroideryRoute
  '/impression/silkscreen': typeof ImpressionSilkscreenRoute
  '/services/promotional-clothing': typeof ServicesPromotionalClothingRoute
  '/impression/': typeof ImpressionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/representants': typeof RepresentantsRoute
  '/impression/dtf': typeof ImpressionDtfRoute
  '/impression/embroidery': typeof ImpressionEmbroideryRoute
  '/impression/silkscreen': typeof ImpressionSilkscreenRoute
  '/services/promotional-clothing': typeof ServicesPromotionalClothingRoute
  '/impression': typeof ImpressionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/impression': typeof ImpressionRouteWithChildren
  '/representants': typeof RepresentantsRoute
  '/impression/dtf': typeof ImpressionDtfRoute
  '/impression/embroidery': typeof ImpressionEmbroideryRoute
  '/impression/silkscreen': typeof ImpressionSilkscreenRoute
  '/services/promotional-clothing': typeof ServicesPromotionalClothingRoute
  '/impression/': typeof ImpressionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/impression'
    | '/representants'
    | '/impression/dtf'
    | '/impression/embroidery'
    | '/impression/silkscreen'
    | '/services/promotional-clothing'
    | '/impression/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/representants'
    | '/impression/dtf'
    | '/impression/embroidery'
    | '/impression/silkscreen'
    | '/services/promotional-clothing'
    | '/impression'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/impression'
    | '/representants'
    | '/impression/dtf'
    | '/impression/embroidery'
    | '/impression/silkscreen'
    | '/services/promotional-clothing'
    | '/impression/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  ImpressionRoute: typeof ImpressionRouteWithChildren
  RepresentantsRoute: typeof RepresentantsRoute
  ServicesPromotionalClothingRoute: typeof ServicesPromotionalClothingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/representants': {
      id: '/representants'
      path: '/representants'
      fullPath: '/representants'
      preLoaderRoute: typeof RepresentantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impression': {
      id: '/impression'
      path: '/impression'
      fullPath: '/impression'
      preLoaderRoute: typeof ImpressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impression/': {
      id: '/impression/'
      path: '/'
      fullPath: '/impression/'
      preLoaderRoute: typeof ImpressionIndexRouteImport
      parentRoute: typeof ImpressionRoute
    }
    '/services/promotional-clothing': {
      id: '/services/promotional-clothing'
      path: '/services/promotional-clothing'
      fullPath: '/services/promotional-clothing'
      preLoaderRoute: typeof ServicesPromotionalClothingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impression/silkscreen': {
      id: '/impression/silkscreen'
      path: '/silkscreen'
      fullPath: '/impression/silkscreen'
      preLoaderRoute: typeof ImpressionSilkscreenRouteImport
      parentRoute: typeof ImpressionRoute
    }
    '/impression/embroidery': {
      id: '/impression/embroidery'
      path: '/embroidery'
      fullPath: '/impression/embroidery'
      preLoaderRoute: typeof ImpressionEmbroideryRouteImport
      parentRoute: typeof ImpressionRoute
    }
    '/impression/dtf': {
      id: '/impression/dtf'
      path: '/dtf'
      fullPath: '/impression/dtf'
      preLoaderRoute: typeof ImpressionDtfRouteImport
      parentRoute: typeof ImpressionRoute
    }
  }
}

interface ImpressionRouteChildren {
  ImpressionDtfRoute: typeof ImpressionDtfRoute
  ImpressionEmbroideryRoute: typeof ImpressionEmbroideryRoute
  ImpressionSilkscreenRoute: typeof ImpressionSilkscreenRoute
  ImpressionIndexRoute: typeof ImpressionIndexRoute
}

const ImpressionRouteChildren: ImpressionRouteChildren = {
  ImpressionDtfRoute: ImpressionDtfRoute,
  ImpressionEmbroideryRoute: ImpressionEmbroideryRoute,
  ImpressionSilkscreenRoute: ImpressionSilkscreenRoute,
  ImpressionIndexRoute: ImpressionIndexRoute,
}

const ImpressionRouteWithChildren = ImpressionRoute._addFileChildren(
  ImpressionRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  ImpressionRoute: ImpressionRouteWithChildren,
  RepresentantsRoute: RepresentantsRoute,
  ServicesPromotionalClothingRoute: ServicesPromotionalClothingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
